{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plotwidgets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plotwidgets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plotwidgets/plotwidgets_{{ version }}.tar.gz
  sha256: 2136053d037091313d75c3f4627128b57c3d11a144be57550f7fe48f93a650d8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('plotwidgets')"           # [not win]
    - "\"%R%\" -e \"library('plotwidgets')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=plotwidgets
  license: GPL (>= 2.0)
  summary: Small self-contained plots for use in larger plots or to delegate plotting in other functions. Also contains a number of alternative color palettes and HSL color space based tools to modify colors or palettes.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - PertuyF

# Package: plotwidgets
# Type: Package
# Title: Spider Plots, ROC Curves, Pie Charts and More for Use in Other Plots
# Version: 0.4
# Date: 2016-09-06
# Author: January Weiner
# Maintainer: January Weiner <january.weiner@gmail.com>
# Description: Small self-contained plots for use in larger plots or to delegate plotting in other functions. Also contains a number of alternative color palettes and HSL color space based tools to modify colors or palettes.
# License: GPL (>= 2.0)
# LazyData: false
# Imports: methods,graphics
# Suggests: testthat,knitr
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-09-06 11:42:27.611 UTC; january
# Repository: CRAN
# Date/Publication: 2016-09-06 14:53:55
