travis:
  secure:
    BINSTAR_TOKEN: c8+npCta+NCTdNjLEbfQj2+hajSm9Jt++VhZ0g6gTAvGCJMi7LJQvL8v4BZ1PN8fXTdtnaQ5BrI5kIArG7dNTvE2mbsqG+pBevd/9IOHgzAYKWN4pUDdWQ0tHgMpPVLoxgXjKwV2JPIjoVwg4V1wRQ1un3Un+vmQWVEW3+kRm5grFJjVgiLq/yIItmCZWUrZs/r4ZuzWMCtzdFxA/g4afknnaMG1FTWwGHhk79Ae7GMQ+7tO+1sc2yYylg8gi/c1Ty4hIVmJYvLOt29cIv5OAI+KXpGK6CZM29rWjpHad7BR6CzDZPe24brJalT1ON1C8At+FNAO6dMZl4IKn6W7cTVVIUhbWr5sgMH8ncQjA2ZFOExjExR2bE7oQQeyK+lHipEC9+v1abR+paDcOBY9YlOZjNkz/Hld8nAUdcsWep4q6UvROQ8Hzq/CBsdIoYoNta98Bl4xP2O6RWpikQefq+epA7FAVZ2euJ5aBqf6Qe0iQ7cCSdncjaey9zMe2L3LXqjwTYDlziiwxu8DrXaA2WJzw5aSVdp+4c+0WUtKMVM/2Pvun906ykLJLzHOQkXa8uTq5IkS87aoOE1oCYF8WTNXr5psNz9GEWk7XyS3RTNusR5Yf+DjriOiiWxHOh0rxac/3ApVZqZC/apf4V3hHBt/aYEDN80+Hf7ZYQvbamo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
